### ISSUE TITLE
Error HA 2024.3.1

### ISSUE THREAD

**Issue by anisakharov** [AlexxIT/Dataplicity#26]
Источник: /usr/local/lib/python3.12/site-packages/dataplicity/client.py:196
Первое сообщение: 16:41:38 (16 сообщений)
Последнее сообщение: 16:56:34

sync failed unable to contact JSONRPC server 'https://api.dataplicity.com' (urlopen error _ssl.c:983: The handshake operation timed out)

Home Assistant
Core
2024.3.1
Supervisor
2024.03.0
Operating System
12.1
Пользовательский интерфейс
20240307.0

**Comment by Gferretta** [comment]
Verify in https://status.dataplicity.com

**Comment by anisakharov** [comment]
Проблема остаётся(((

**Comment by riddik14** [comment]
2024-04-03 19:39:22.564 ERROR (m2m) [m2m] error handling websocket event
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/dataplicity/m2m/wsclient.py", line 265, in run
    self.on_event(event)
  File "/usr/local/lib/python3.12/site-packages/dataplicity/m2m/wsclient.py", line 281, in on_event
    self.on_binary(event.data)
  File "/usr/local/lib/python3.12/site-packages/dataplicity/m2m/wsclient.py", line 327, in on_binary
    self.on_packet(packet)
  File "/usr/local/lib/python3.12/site-packages/dataplicity/m2m/wsclient.py", line 347, in on_packet
    self.dispatcher.dispatch(packet_type, packet_body)
  File "/usr/local/lib/python3.12/site-packages/dataplicity/m2m/dispatcher.py", line 80, in dispatch
    return self.dispatch_packet(packet)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dataplicity/m2m/dispatcher.py", line 101, in dispatch_packet
    ret = method(packet_type, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dataplicity/m2m/wsclient.py", line 408, in handle_route
    channel.on_data(data)
  File "/usr/local/lib/python3.12/site-packages/dataplicity/m2m/wsclient.py", line 95, in on_data
    self._data_callback(data)
  File "/usr/local/lib/python3.12/site-packages/dataplicity/portforward.py", line 172, in on_channel_data
    self._flush_buffer()
  File "/usr/local/lib/python3.12/site-packages/dataplicity/portforward.py", line 179, in _flush_buffer
    self.socket.sendall(chunk)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by AlexxIT** [comment]
Some problems with connection to dataplicity servers. Not related to this integration.
